// webpack.build-client.config.js
const path = require('path');
const WebpackObfuscator = require('webpack-obfuscator');

module.exports = {
  // Point this at the file generated by builder.py
  // e.g. python builder.py --name messenger-client.built.js
  entry: path.resolve(__dirname, 'client.js'),

  output: {
      path: __dirname,        // <- output to current directory
    filename: 'client.obf.js',
  },

  target: 'node',

  mode: 'production',
  devtool: false,

  optimization: {
    minimize: true,
  },

  plugins: [
    new WebpackObfuscator(
      {
        compact: true,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 0.75,
        deadCodeInjection: true,
        deadCodeInjectionThreshold: 0.4,
        debugProtection: false,
        disableConsoleOutput: true,
        identifierNamesGenerator: 'hexadecimal',
        renameGlobals: false,
        rotateStringArray: true,
        selfDefending: true,
        simplify: true,
        splitStrings: true,
        splitStringsChunkLength: 10,
        stringArray: true,
        stringArrayEncoding: ['base64'],
        stringArrayThreshold: 0.75,
        transformObjectKeys: true,
        unicodeEscapeSequence: false,
      },
      []
    ),
  ],
};
